server:
  port: 9999

security:
  ignore-paths:
    - "/login/**"
    - "/oauth2/**"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/nopecho
    username: nopecho
    password: nopecho

  security:
    oauth2:
      client:
        registration:
          google:
            # ${OAUTH2_GOOGLE_CLIENT_ID}
            client-id: local
            # ${OAUTH2_GOOGLE_CLIENT_SECRET}
            client-secret: local
            scope:
              - profile
              - email
          kakao:
            # ${OAUTH2_KAKAO_CLIENT_ID}
            client-id: local
            # ${OAUTH2_KAKAO_CLIENT_SECRET}
            client-secret: local
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9999/login/oauth2/code/kakao
            client-authentication-method: POST
          naver:
            # ${OAUTH2_NAVER_CLIENT_ID}
            client-id: local
            # ${OAUTH2_NAVER_CLIENT_SECRET}
            client-secret: local
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9999/login/oauth2/code/naver
          apple:
            # ${OAUTH2_APPLE_CLIENT_ID}
            client-id: local
            # ${OAUTH2_APPLE_CLIENT_SECRET}
            client-secret: local
            scope:
              - name
              - email
            client-name: Apple
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9999/login/oauth2/code/apple

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://appleid.apple.com/auth/userinfo"
            user-name-attribute: sub

